using System.Globalization;
using System.Text;

namespace Rc2Axaml;

/// <summary>
/// Writes one AXAML <c>UserControl</c> per dialog, laid out on a <c>Canvas</c>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Canvas, not a real layout panel, and on purpose.</b> An MFC dialog is a flat list of
/// absolutely-positioned rectangles with no containment: a <c>GROUPBOX</c> does not own the
/// controls drawn inside it, it is just another rectangle that happens to surround them.
/// Reconstructing grids and stack panels from coordinates is guesswork that gets 131 dialogs
/// subtly wrong; reproducing the coordinates gets them all exactly right and leaves the
/// restructuring to the hand pass that has to touch each dialog anyway.
/// </para>
/// <para>
/// <b>No <c>x:Class</c>, so no code-behind.</b> These files are raw material. A generated file
/// with an <c>x:Class</c> would demand a matching partial class that does not exist and break the
/// build of any project that globs them.
/// </para>
/// </remarks>
public static class AxamlEmitter
{
    /// <summary>Converts one dialog to AXAML.</summary>
    /// <param name="dialog">The parsed dialog.</param>
    /// <param name="sourcePath">
    /// Path to cite in the provenance comment, relative to the repository root — the generated
    /// file is worthless without a pointer back to the statement it came from.
    /// </param>
    /// <param name="diagnostics">Collects anything that could not be mapped faithfully.</param>
    public static string Emit(RcDialog dialog, string sourcePath, IList<string> diagnostics)
    {
        DialogUnits units = DialogUnits.ForFont(dialog.Font, diagnostics);
        (_, _, int width, int height) = units.MapRect(0, 0, dialog.Width, dialog.Height);

        var output = new StringBuilder();
        output.Append("<!--\n");
        output.Append(CultureInfo.InvariantCulture, $"  {dialog.Id} — generated by tools/rc2axaml from {sourcePath}:{dialog.SourceLine}.\n");
        if (dialog.Caption is not null)
        {
            // The caption is the only free text in this header, so it is the only part that could
            // carry a "--" and turn the provenance comment into a parse error.
            output.Append(CultureInfo.InvariantCulture, $"  CAPTION \"{EscapeComment(dialog.Caption)}\"\n");
        }

        output.Append(CultureInfo.InvariantCulture,
            $"  {dialog.Width} x {dialog.Height} dialog units at FONT {dialog.Font.PointSize}, \"{dialog.Font.Face}\" " +
            $"(base units {units.BaseUnitX} x {units.BaseUnitY}) = {width} x {height} px.\n");
        output.Append("\n  Not hand-edited and not wired into a project: regenerate rather than patch, or move the\n");
        output.Append("  file out of Views/Generated once a real view takes it over.\n");
        output.Append("-->\n");

        output.Append("<UserControl xmlns=\"https://github.com/avaloniaui\"\n");
        output.Append("             xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"\n");
        output.Append(CultureInfo.InvariantCulture, $"             Width=\"{width}\" Height=\"{height}\">\n");
        output.Append(CultureInfo.InvariantCulture, $"  <Canvas Width=\"{width}\" Height=\"{height}\">\n");

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        int radioGroup = 0;

        foreach (RcControl control in dialog.Controls)
        {
            // WS_GROUP marks the first control of a Win32 group; every control after it belongs to
            // that group until the next WS_GROUP. Radio buttons are the only consumers here, but
            // the counter has to advance on every control or the runs come out wrong.
            if (control.HasStyle("WS_GROUP")) { radioGroup++; }

            MappedControl mapped = ControlMap.Map(control, dialog.Id, radioGroup, diagnostics);
            output.Append(RenderControl(control, mapped, units, dialog.Id, usedNames, diagnostics));
        }

        output.Append("  </Canvas>\n");
        output.Append("</UserControl>\n");
        return output.ToString();
    }

    private static string RenderControl(
        RcControl control,
        MappedControl mapped,
        DialogUnits units,
        string dialogId,
        HashSet<string> usedNames,
        IList<string> diagnostics)
    {
        int cy = control.Keyword == "COMBOBOX" ? ControlMap.ClosedComboHeightDlu : control.Height;
        (int left, int top, int width, int height) = units.MapRect(control.X, control.Y, control.Width, cy);

        var element = new StringBuilder("    <").Append(mapped.Element);

        if (control.HasRealId)
        {
            string name = UniqueName(control.Id, usedNames, dialogId, control.SourceLine, diagnostics);
            element.Append(CultureInfo.InvariantCulture, $" x:Name=\"{name}\"");
        }

        element.Append(CultureInfo.InvariantCulture, $" Canvas.Left=\"{left}\" Canvas.Top=\"{top}\"");
        element.Append(CultureInfo.InvariantCulture, $" Width=\"{width}\" Height=\"{height}\"");

        foreach ((string attribute, string value) in mapped.Attributes)
        {
            element.Append(CultureInfo.InvariantCulture, $" {attribute}=\"{EscapeAttribute(value)}\"");
        }

        element.Append(" />");

        if (mapped.Note is not null)
        {
            element.Append(CultureInfo.InvariantCulture, $" <!-- {EscapeComment(mapped.Note)} -->");
        }

        return element.Append('\n').ToString();
    }

    /// <summary>
    /// Turns a resource identifier into an <c>x:Name</c>, keeping names unique within the dialog.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Duplicates are legal in a resource script and meaningful in MFC — several controls sharing
    /// one id is how the original addressed them as a set — but XAML names are unique per name
    /// scope, so a suffix is added and the collision is reported. No dialog in UAFWinEd.rc actually
    /// collides once <c>-1</c> is excluded from naming; the two that looked like they did were
    /// eleven anonymous statements written as <c>-1</c> rather than <c>IDC_STATIC</c>.
    /// </para>
    /// <para>
    /// The <c>Id</c> prefix is for the one control whose identifier is a bare number
    /// (<c>1119</c> = <c>stc32</c>, see <see cref="RcControl.HasRealId"/>). Dropping it would lose
    /// the only thing that says which static the file dialog is looking for.
    /// </para>
    /// </remarks>
    private static string UniqueName(
        string id, HashSet<string> usedNames, string dialogId, int line, IList<string> diagnostics)
    {
        var name = new StringBuilder(id.Length + 2);
        if (!char.IsLetter(id[0]) && id[0] != '_') { name.Append("Id"); }
        foreach (char c in id) { name.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_'); }

        string candidate = name.ToString();
        if (usedNames.Add(candidate)) { return candidate; }

        int suffix = 2;
        while (!usedNames.Add($"{candidate}_{suffix}")) { suffix++; }
        diagnostics.Add($"{dialogId} (line {line}): duplicate control id '{id}', named '{candidate}_{suffix}'");
        return $"{candidate}_{suffix}";
    }

    /// <summary>
    /// Escapes an attribute value, including the newlines that <c>\n</c> in a label becomes.
    /// </summary>
    /// <remarks>
    /// A raw newline inside an XML attribute is legal but is normalised to a space by every
    /// conforming parser, so the About box's two-line copyright would silently collapse onto one
    /// line. The numeric reference survives attribute-value normalisation.
    /// </remarks>
    private static string EscapeAttribute(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal)
        .Replace("\r\n", "&#10;", StringComparison.Ordinal)
        .Replace("\n", "&#10;", StringComparison.Ordinal)
        .Replace("\r", "&#10;", StringComparison.Ordinal)
        .Replace("\t", "&#9;", StringComparison.Ordinal);

    /// <summary>XML comments cannot contain <c>--</c> and cannot end with <c>-</c>.</summary>
    private static string EscapeComment(string value)
    {
        string cleaned = value.Replace("--", "-", StringComparison.Ordinal).Replace('\n', ' ').Replace('\r', ' ');
        return cleaned.EndsWith('-') ? cleaned + " " : cleaned;
    }
}
