// <auto-generated>
//     Generated by dotnet/tools/gen-combat-tiles.py from src/UAFWin/Drawtile.cpp.
//     Do not edit by hand; re-run the generator and diff.
// </auto-generated>

namespace UAFcore;

public static partial class CombatTiles
{
    /// <summary>
    /// <c>DungeonWallTiles</c> — 26 tiles, index 0 unused.
    /// </summary>
    public static readonly CombatTile[] Dungeon =
    [
        new(0, 0, SeeThrough: false, Passable: false, Enabled: false),   // unused placeholder
        new(2, 2, SeeThrough: false, Passable: false, Enabled: true),   // 1
        new(62, 2, SeeThrough: false, Passable: false, Enabled: true),   // 2
        new(122, 2, SeeThrough: false, Passable: false, Enabled: true),   // 3
        new(182, 2, SeeThrough: false, Passable: false, Enabled: true),   // 4
        new(242, 2, SeeThrough: true, Passable: true, Enabled: true),   // 5
        new(302, 2, SeeThrough: false, Passable: false, Enabled: true),   // 6
        new(362, 2, SeeThrough: false, Passable: false, Enabled: true),   // 7
        new(422, 2, SeeThrough: false, Passable: false, Enabled: true),   // 8
        new(482, 2, SeeThrough: true, Passable: true, Enabled: true),   // 9
        new(542, 2, SeeThrough: false, Passable: false, Enabled: true),   // 10
        new(2, 62, SeeThrough: true, Passable: true, Enabled: true),   // 11
        new(62, 62, SeeThrough: false, Passable: false, Enabled: true),   // 12
        new(122, 62, SeeThrough: true, Passable: true, Enabled: true),   // 13
        new(182, 62, SeeThrough: false, Passable: false, Enabled: true),   // 14
        new(242, 62, SeeThrough: true, Passable: true, Enabled: true),   // 15
        new(302, 62, SeeThrough: false, Passable: false, Enabled: true),   // 16
        new(362, 62, SeeThrough: true, Passable: true, Enabled: true),   // 17
        new(422, 62, SeeThrough: false, Passable: false, Enabled: true),   // 18
        new(482, 62, SeeThrough: false, Passable: false, Enabled: true),   // 19
        new(542, 62, SeeThrough: false, Passable: false, Enabled: true),   // 20
        new(2, 122, SeeThrough: false, Passable: false, Enabled: true),   // 21
        new(62, 122, SeeThrough: false, Passable: false, Enabled: true),   // 22
        new(122, 122, SeeThrough: true, Passable: true, Enabled: true),   // 23
        new(182, 122, SeeThrough: true, Passable: true, Enabled: true),   // 24
        new(242, 122, SeeThrough: false, Passable: false, Enabled: true),   // 25
        new(302, 122, SeeThrough: true, Passable: true, Enabled: false),   // 26
    ];

    /// <summary>The tile holes in the dungeon map are filled with (<c>DUNGEON_EMPTY_TILE</c>).</summary>
    public const int DungeonEmptyTile = 23;

    /// <summary>
    /// <c>WildernessWallTiles</c> — 40 tiles, index 0 unused.
    /// </summary>
    public static readonly CombatTile[] Wilderness =
    [
        new(0, 0, SeeThrough: false, Passable: false, Enabled: false),   // unused placeholder
        new(2, 2, SeeThrough: false, Passable: false, Enabled: true),   // 1
        new(62, 2, SeeThrough: false, Passable: false, Enabled: true),   // 2
        new(122, 2, SeeThrough: false, Passable: false, Enabled: true),   // 3
        new(182, 2, SeeThrough: false, Passable: false, Enabled: true),   // 4
        new(242, 2, SeeThrough: false, Passable: false, Enabled: true),   // 5
        new(302, 2, SeeThrough: true, Passable: false, Enabled: false),   // 6
        new(362, 2, SeeThrough: true, Passable: false, Enabled: false),   // 7
        new(422, 2, SeeThrough: true, Passable: false, Enabled: false),   // 8
        new(482, 2, SeeThrough: true, Passable: false, Enabled: false),   // 9
        new(542, 2, SeeThrough: true, Passable: false, Enabled: false),   // 10
        new(2, 62, SeeThrough: true, Passable: true, Enabled: true),   // 11
        new(62, 62, SeeThrough: true, Passable: true, Enabled: true),   // 12
        new(122, 62, SeeThrough: true, Passable: true, Enabled: true),   // 13
        new(182, 62, SeeThrough: true, Passable: true, Enabled: true),   // 14
        new(242, 62, SeeThrough: true, Passable: true, Enabled: true),   // 15
        new(302, 62, SeeThrough: true, Passable: false, Enabled: false),   // 16
        new(362, 62, SeeThrough: true, Passable: false, Enabled: false),   // 17
        new(422, 62, SeeThrough: true, Passable: false, Enabled: false),   // 18
        new(482, 62, SeeThrough: true, Passable: false, Enabled: false),   // 19
        new(542, 62, SeeThrough: true, Passable: false, Enabled: false),   // 20
        new(2, 122, SeeThrough: true, Passable: false, Enabled: true),   // 21
        new(62, 122, SeeThrough: true, Passable: false, Enabled: true),   // 22
        new(122, 122, SeeThrough: true, Passable: false, Enabled: true),   // 23
        new(182, 122, SeeThrough: true, Passable: true, Enabled: true),   // 24
        new(242, 122, SeeThrough: true, Passable: true, Enabled: true),   // 25
        new(302, 122, SeeThrough: true, Passable: false, Enabled: true),   // 26
        new(362, 122, SeeThrough: true, Passable: false, Enabled: true),   // 27
        new(422, 122, SeeThrough: true, Passable: false, Enabled: true),   // 28
        new(482, 122, SeeThrough: true, Passable: true, Enabled: true),   // 29
        new(542, 122, SeeThrough: true, Passable: true, Enabled: true),   // 30
        new(2, 182, SeeThrough: true, Passable: true, Enabled: true),   // 31
        new(62, 182, SeeThrough: true, Passable: true, Enabled: true),   // 32
        new(122, 182, SeeThrough: true, Passable: true, Enabled: true),   // 33
        new(182, 182, SeeThrough: true, Passable: true, Enabled: true),   // 34
        new(242, 182, SeeThrough: true, Passable: true, Enabled: true),   // 35
        new(302, 182, SeeThrough: true, Passable: false, Enabled: true),   // 36
        new(362, 182, SeeThrough: true, Passable: true, Enabled: true),   // 37
        new(422, 182, SeeThrough: true, Passable: true, Enabled: true),   // 38
        new(482, 182, SeeThrough: true, Passable: false, Enabled: false),   // 39
        new(542, 182, SeeThrough: true, Passable: false, Enabled: false),   // 40
    ];

    /// <summary>The tile holes in the wilderness map are filled with (<c>WILDERNESS_EMPTY_TILE</c>).</summary>
    public const int WildernessEmptyTile = 38;
}
