// <auto-generated>
//     Generated by dotnet/tools/gen-party-arrangements.py from src/UAFWin/Combatants.cpp.
//     Do not edit by hand; re-run the generator and diff.
// </auto-generated>

namespace UAFcore;

public static partial class PartyArrangements
{
    /// <summary>Longest party the tables describe (<c>MAX_PARTY_MEMBERS</c>).</summary>
    public const int MaxPartyMembers = 12;

    /// <summary>Characters per direction block.</summary>
    public const int DirectionBlock = 156;

    /// <summary>
    /// <c>partyIndoorCombatArrangement</c> — four direction blocks of 156 characters.
    /// </summary>
    /// <remarks>
    /// <code>
    /// north:
    ///    1: AB
    ///    2: ABBB
    ///    3: bBABBB
    ///    4: ABBBBCCC
    ///    5: bBABBBBCCC
    ///    6: bBABBBACCCBC
    ///    7: bBABBBCBACCCBC
    ///    8: bBABBBCBACDCBCCC
    ///    9: cBbBABBBCBACDCBCCC
    ///   10: cBbBABBBCBbCACDCBCCC
    ///   11: cBbBABBBCBDBbCACDCBCCC
    ///   12: cBbBABBBCBDBbCACDCBCECCC
    /// east:
    ///    1: bA
    ///    2: bAAB
    ///    3: cbbAAB
    ///    4: bAABcAbB
    ///    5: cbbAABcAbB
    ///    6: cbbAABdbbBcA
    ///    7: cbbAABBCdbbBcA
    ///    8: cbbAABBCdbACcAbB
    ///    9: dccbbAABBCdbACcAbB
    ///   10: dccbbAABBCecACdbcAbB
    ///   11: dccbbAABBCCDecACdbcAbB
    ///   12: dccbbAABBCCDecBDdbcAbBAC
    /// south:
    ///    1: AA
    ///    2: AAbA
    ///    3: BAAAbA
    ///    4: AAbAbbcb
    ///    5: BAAAbAbbcb
    ///    6: BAAAbAAbcbbb
    ///    7: CABAAAbAAbcbbb
    ///    8: CABAAAbABbcbAbbb
    ///    9: CABAAAbAcABbcbAbbb
    ///   10: CABAAAbAcABbdbcbAbbb
    ///   11: DACABAAAbAcABbdbcbAbbb
    ///   12: DACABAAAbAcACbdbBbcbAbbb
    /// west:
    ///    1: BB
    ///    2: BBAA
    ///    3: CCBBAA
    ///    4: BBAACBBA
    ///    5: CCBBAACBBA
    ///    6: CCBBAADCBACB
    ///    7: CCBBAAbbDCBACB
    ///    8: CCBBAAbbDCAbCBBA
    ///    9: CCBBAAbbccDCAbCBBA
    ///   10: CCBBAAbbccDCbcAbCBBA
    ///   11: DDCCBBAAbbccDCbcAbCBBA
    ///   12: DDCCBBAAbbccEDbcAbDCCBBA
    /// </code>
    /// </remarks>
    public const string Indoor =
        "ABABBBbBABBBABBBBCCCbBABBBBCCCbBABBBACCCBCbBABBBCBACCCBCbBABBBCBACDCBCCCcBbBAB" +
        "BBCBACDCBCCCcBbBABBBCBbCACDCBCCCcBbBABBBCBDBbCACDCBCCCcBbBABBBCBDBbCACDCBCECCC" +
        "bAbAABcbbAABbAABcAbBcbbAABcAbBcbbAABdbbBcAcbbAABBCdbbBcAcbbAABBCdbACcAbBdccbbA" +
        "ABBCdbACcAbBdccbbAABBCecACdbcAbBdccbbAABBCCDecACdbcAbBdccbbAABBCCDecBDdbcAbBAC" +
        "AAAAbABAAAbAAAbAbbcbBAAAbAbbcbBAAAbAAbcbbbCABAAAbAAbcbbbCABAAAbABbcbAbbbCABAAA" +
        "bAcABbcbAbbbCABAAAbAcABbdbcbAbbbDACABAAAbAcABbdbcbAbbbDACABAAAbAcACbdbBbcbAbbb" +
        "BBBBAACCBBAABBAACBBACCBBAACBBACCBBAADCBACBCCBBAAbbDCBACBCCBBAAbbDCAbCBBACCBBAA" +
        "bbccDCAbCBBACCBBAAbbccDCbcAbCBBADDCCBBAAbbccDCbcAbCBBADDCCBBAAbbccEDbcAbDCCBBA";

    /// <summary>
    /// <c>partyOutdoorCombatArrangement</c> — four direction blocks of 156 characters.
    /// </summary>
    /// <remarks>
    /// <code>
    /// north:
    ///    1: AB
    ///    2: ABBB
    ///    3: bBABBB
    ///    4: bBABBBCB
    ///    5: cBbBABBBCB
    ///    6: cBbbABBBCBDB
    ///    7: dBcBbBABBBCBDB
    ///    8: eBdBcBbBABBBCBDB
    ///    9: eBdBcBbBABBBCBDBEB
    ///   10: fBeBdBcBbBABBBCBDBEB
    ///   11: fBeBdBcBbBABBBCBDBEBFB
    ///   12: gBfBeBdBcBbBABBBCBDBEBFB
    /// east:
    ///    1: bA
    ///    2: bAAB
    ///    3: cbbAAB
    ///    4: cbbAABBC
    ///    5: dccbbAABBC
    ///    6: dccbbAABBCCD
    ///    7: eddccbbAABBCCD
    ///    8: eddccbbAABBCCDDE
    ///    9: feeddccbbAABBCCDDE
    ///   10: feeddccbbAABBCCDDEEF
    ///   11: gffeeddccbbAABBCCDDEEF
    ///   12: gffeeddccbbAABBCCDDEEFFG
    /// south:
    ///    1: AA
    ///    2: AAbA
    ///    3: BAAAbA
    ///    4: CABAAAbA
    ///    5: CABAAAbAbA
    ///    6: DACABAAAbAcA
    ///    7: DACABAAAbAcAdA
    ///    8: EADACABAAAbAcAdA
    ///    9: EADACABAAAbAcAdAeA
    ///   10: FAEADACABAAAbAcAdAeA
    ///   11: FAEADACABAAAbAcAdAeAfA
    ///   12: GAFAEADACABAAAbAcAdAeAfA
    /// west:
    ///    1: BB
    ///    2: BBAA
    ///    3: CCBBAA
    ///    4: CCBBAAbb
    ///    5: DDCCBBAAbb
    ///    6: DDCCBBAAbbcc
    ///    7: EEDDCCBBAAbbcc
    ///    8: EEDDCCBBAAbbccdd
    ///    9: FFEEDDCCBBAAbbccdd
    ///   10: FFEEDDCCBBAAbbccddee
    ///   11: GGFFEEDDCCBBAAbbccddee
    ///   12: GGFFEEDDCCBBAAbbccddeeff
    /// </code>
    /// </remarks>
    public const string Outdoor =
        "ABABBBbBABBBbBABBBCBcBbBABBBCBcBbbABBBCBDBdBcBbBABBBCBDBeBdBcBbBABBBCBDBeBdBcB" +
        "bBABBBCBDBEBfBeBdBcBbBABBBCBDBEBfBeBdBcBbBABBBCBDBEBFBgBfBeBdBcBbBABBBCBDBEBFB" +
        "bAbAABcbbAABcbbAABBCdccbbAABBCdccbbAABBCCDeddccbbAABBCCDeddccbbAABBCCDDEfeeddc" +
        "cbbAABBCCDDEfeeddccbbAABBCCDDEEFgffeeddccbbAABBCCDDEEFgffeeddccbbAABBCCDDEEFFG" +
        "AAAAbABAAAbACABAAAbACABAAAbAbADACABAAAbAcADACABAAAbAcAdAEADACABAAAbAcAdAEADACA" +
        "BAAAbAcAdAeAFAEADACABAAAbAcAdAeAFAEADACABAAAbAcAdAeAfAGAFAEADACABAAAbAcAdAeAfA" +
        "BBBBAACCBBAACCBBAAbbDDCCBBAAbbDDCCBBAAbbccEEDDCCBBAAbbccEEDDCCBBAAbbccddFFEEDD" +
        "CCBBAAbbccddFFEEDDCCBBAAbbccddeeGGFFEEDDCCBBAAbbccddeeGGFFEEDDCCBBAAbbccddeeff";
}
