using System.Security.Cryptography;

namespace UAF.Media.Tests;

/// <summary>
/// Diffs <see cref="PngDecoder"/> against an independent decode of every PNG in the reference
/// designs.
/// </summary>
/// <remarks>
/// <para>
/// The same tactic that carried the serialization port: decode the real files with an
/// implementation sharing no code with ours and compare. The oracle here is Pillow, which wraps
/// libpng — the very library the C++ used. Digests live in <c>Assets/png-oracle.txt</c> and are
/// regenerated by <c>tools/art-oracle.py</c>; committing them means this runs with no Python
/// present, exactly as the committed C++ dump does for serialization.
/// </para>
/// <para>
/// The art itself is gitignored, so these tests return early when the corpus is absent. That
/// makes them local-only in practice. It is worth being blunt about that: on a CI runner without
/// the designs, this file proves nothing.
/// </para>
/// </remarks>
public class PngOracleTests
{
    private sealed record OracleEntry(string RelativePath, int Width, int Height, string Sha256);

    /// <summary>
    /// The reference art corpus, or null when this checkout does not carry it.
    /// </summary>
    /// <remarks>
    /// The probe is a file the manifest names, <b>not</b> the <c>reference/</c> directory. The .NET
    /// workflow creates that directory itself to hold the tier-3 data fixture it fetches
    /// (<c>mkdir -p reference/dc-default</c>), so its existence answers "did the workflow run
    /// mkdir", not "is the art here". Guarding on the directory turned the early return into three
    /// hard failures on every CI platform.
    /// </remarks>
    private static string? CorpusRoot(IReadOnlyList<OracleEntry> oracle)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "src", "Shared")))
        {
            dir = dir.Parent;
        }

        if (dir is null)
        {
            return null;
        }

        string root = Path.Combine(dir.FullName, "reference");
        return File.Exists(Resolve(root, oracle[0])) ? root : null;
    }

    private static string Resolve(string root, OracleEntry entry) =>
        Path.Combine(root, entry.RelativePath.Replace('/', Path.DirectorySeparatorChar));

    private static List<OracleEntry> LoadOracle()
    {
        var entries = new List<OracleEntry>();
        foreach (string line in File.ReadLines(TestPaths.Asset("png-oracle.txt")))
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            string[] fields = line.Split('|');
            entries.Add(new OracleEntry(fields[0], int.Parse(fields[1]), int.Parse(fields[2]),
                                        fields[3]));
        }
        return entries;
    }

    /// <summary>
    /// Hashes the decoded pixels as RGB triples, dropping the alpha byte so the digest matches what
    /// the oracle produced from <c>Image.convert("RGB")</c>.
    /// </summary>
    private static string Digest(DecodedImage image)
    {
        var rgb = new byte[image.Pixels.Length * 3];
        for (int i = 0; i < image.Pixels.Length; i++)
        {
            uint pixel = image.Pixels[i];
            rgb[i * 3] = (byte)(pixel >> 16);
            rgb[(i * 3) + 1] = (byte)(pixel >> 8);
            rgb[(i * 3) + 2] = (byte)pixel;
        }
        return Convert.ToHexStringLower(SHA256.HashData(rgb));
    }

    [Fact]
    public void Every_reference_png_decodes_to_the_same_pixels_as_libpng()
    {
        // The manifest is committed, so it must parse everywhere; only the art it names is
        // optional. Asserting on it before the corpus guard keeps a lost manifest a failure
        // rather than a silent skip.
        var oracle = LoadOracle();
        Assert.NotEmpty(oracle);

        if (CorpusRoot(oracle) is not { } root)
        {
            return;
        }

        var mismatches = new List<string>();
        int checked_ = 0;

        foreach (var entry in oracle)
        {
            string path = Resolve(root, entry);
            if (!File.Exists(path))
            {
                continue;
            }

            checked_++;
            DecodedImage image;
            try
            {
                image = ImageLoader.Default.Load(path);
            }
            catch (Exception e)
            {
                mismatches.Add($"{entry.RelativePath}: threw {e.GetType().Name}: {e.Message}");
                continue;
            }

            if (image.Width != entry.Width || image.Height != entry.Height)
            {
                mismatches.Add($"{entry.RelativePath}: got {image.Width}x{image.Height}, " +
                               $"oracle says {entry.Width}x{entry.Height}");
                continue;
            }

            string digest = Digest(image);
            if (digest != entry.Sha256)
            {
                mismatches.Add($"{entry.RelativePath}: pixels differ " +
                               $"({digest[..12]} vs oracle {entry.Sha256[..12]})");
            }
        }

        // A file list rather than a count: with 1300 files, "17 failed" is not actionable and the
        // first few paths usually identify the colour type or filter at fault immediately.
        Assert.True(mismatches.Count == 0,
            $"{mismatches.Count} of {checked_} files differ from libpng:\n  " +
            string.Join("\n  ", mismatches.Take(20)));

        Assert.True(checked_ > 1000, $"only {checked_} files were checked; expected the full corpus");
    }

    [Fact]
    public void Decoded_art_is_always_opaque()
    {
        var oracle = LoadOracle();
        Assert.NotEmpty(oracle);

        if (CorpusRoot(oracle) is not { } root)
        {
            return;
        }

        // The strip-alpha contract, checked on the files that actually have an alpha channel to
        // strip. If this ever fails, keyed blits break in a way that only shows on sprite art.
        var withAlpha = oracle
            .Select(e => Resolve(root, e))
            .Where(File.Exists)
            .Where(p => ColorTypeOf(p) is 4 or 6)
            .ToList();

        Assert.NotEmpty(withAlpha);

        foreach (string path in withAlpha)
        {
            var image = ImageLoader.Default.Load(path);
            Assert.All(image.Pixels, p => Assert.Equal(0xFF000000u, p & 0xFF000000u));
        }
    }

    /// <summary>The IHDR colour-type byte, read without decoding the image.</summary>
    private static int ColorTypeOf(string path)
    {
        using var stream = File.OpenRead(path);
        Span<byte> head = stackalloc byte[26];
        stream.ReadExactly(head);
        return head[25];
    }

    [Fact]
    public void The_corpus_covers_the_colour_types_the_decoder_claims_to_handle()
    {
        var oracle = LoadOracle();
        Assert.NotEmpty(oracle);

        if (CorpusRoot(oracle) is not { } root)
        {
            return;
        }

        var byType = oracle
            .Select(e => Resolve(root, e))
            .Where(File.Exists)
            .GroupBy(ColorTypeOf)
            .ToDictionary(g => g.Key, g => g.Count());

        // Documents what the oracle run actually exercises, so a future change that breaks the
        // palette path cannot hide behind 1286 truecolour files passing. Truecolour: 1286,
        // truecolour+alpha: 14, palette: 12 -- and nothing greyscale or 16-bit at all, which is
        // why those paths are covered only by the synthetic tests.
        Assert.True(byType.GetValueOrDefault(2) > 1000, "expected truecolour art");
        Assert.True(byType.GetValueOrDefault(6) > 0, "expected truecolour+alpha art");
        Assert.True(byType.GetValueOrDefault(3) > 0, "expected palette art");
    }
}
