// <auto-generated>
//     Generated by dotnet/tools/gen-design-versions.py from the legacy C++ headers.
//     Do not edit by hand. Re-run the generator and commit the result instead.
//
//     Sources: src/Shared/Externs.h, src/Shared/Globals.cpp
//     (src/Shared/ProjectVersion.h is dead code and is deliberately ignored.)
// </auto-generated>

namespace UAF.Common;

public readonly partial struct DesignVersion
{
    /// <summary>C++ <c>_VERSION_0500_</c> (Externs.h).</summary>
    public static DesignVersion V0500 => new(0.500);
    /// <summary>C++ <c>_VERSION_0505_</c> (Externs.h).</summary>
    public static DesignVersion V0505 => new(0.505);
    /// <summary>C++ <c>_VERSION_0560_</c> (Externs.h).</summary>
    public static DesignVersion V0560 => new(0.560);
    /// <summary>C++ <c>_VERSION_0563_</c> (Externs.h).</summary>
    public static DesignVersion V0563 => new(0.563);
    /// <summary>C++ <c>_VERSION_0564_</c> (Externs.h).</summary>
    public static DesignVersion V0564 => new(0.564);
    /// <summary>C++ <c>_VERSION_0566_</c> (Externs.h).</summary>
    public static DesignVersion V0566 => new(0.566);
    /// <summary>C++ <c>_VERSION_05661_</c> (Externs.h).</summary>
    public static DesignVersion V05661 => new(0.5661);
    /// <summary>C++ <c>_VERSION_05662_</c> (Externs.h).</summary>
    public static DesignVersion V05662 => new(0.5662);
    /// <summary>C++ <c>_VERSION_0569_</c> (Externs.h).</summary>
    public static DesignVersion V0569 => new(0.569);
    /// <summary>C++ <c>_VERSION_05691_</c> (Externs.h).</summary>
    public static DesignVersion V05691 => new(0.5691);
    /// <summary>C++ <c>_VERSION_0572_</c> (Externs.h).</summary>
    public static DesignVersion V0572 => new(0.572);
    /// <summary>C++ <c>_VERSION_0573_</c> (Externs.h).</summary>
    public static DesignVersion V0573 => new(0.573);
    /// <summary>C++ <c>_VERSION_0574_</c> (Externs.h).</summary>
    public static DesignVersion V0574 => new(0.574);
    /// <summary>C++ <c>_VERSION_0575_</c> (Externs.h).</summary>
    public static DesignVersion V0575 => new(0.575);
    /// <summary>C++ <c>_VERSION_0576_</c> (Externs.h).</summary>
    public static DesignVersion V0576 => new(0.576);
    /// <summary>C++ <c>_VERSION_05771_</c> (Externs.h).</summary>
    public static DesignVersion V05771 => new(0.5771);
    /// <summary>C++ <c>_VERSION_0600_</c> (Externs.h).</summary>
    public static DesignVersion V0600 => new(0.6000);
    /// <summary>C++ <c>_VERSION_0620_</c> (Externs.h).</summary>
    public static DesignVersion V0620 => new(0.6200);
    /// <summary>C++ <c>_VERSION_0630_</c> (Externs.h).</summary>
    public static DesignVersion V0630 => new(0.6300);
    /// <summary>C++ <c>_VERSION_0640_</c> (Externs.h).</summary>
    public static DesignVersion V0640 => new(0.6400);
    /// <summary>C++ <c>_VERSION_0642_</c> (Externs.h).</summary>
    public static DesignVersion V0642 => new(0.6420);
    /// <summary>C++ <c>_VERSION_0660_</c> (Externs.h).</summary>
    public static DesignVersion V0660 => new(0.6600);
    /// <summary>C++ <c>_VERSION_0661_</c> (Externs.h).</summary>
    public static DesignVersion V0661 => new(0.6610);
    /// <summary>C++ <c>_VERSION_0662_</c> (Externs.h).</summary>
    public static DesignVersion V0662 => new(0.6620);
    /// <summary>C++ <c>_VERSION_0670_</c> (Externs.h).</summary>
    public static DesignVersion V0670 => new(0.6700);
    /// <summary>C++ <c>_VERSION_0681_</c> (Externs.h).</summary>
    public static DesignVersion V0681 => new(0.6810);
    /// <summary>C++ <c>_VERSION_0682_</c> (Externs.h).</summary>
    public static DesignVersion V0682 => new(0.6820);
    /// <summary>C++ <c>_VERSION_0690_</c> (Externs.h).</summary>
    public static DesignVersion V0690 => new(0.6900);
    /// <summary>C++ <c>_VERSION_0692_</c> (Externs.h).</summary>
    public static DesignVersion V0692 => new(0.6920);
    /// <summary>C++ <c>_VERSION_0693_</c> (Externs.h).</summary>
    public static DesignVersion V0693 => new(0.6930);
    /// <summary>C++ <c>_VERSION_0694_</c> (Externs.h).</summary>
    public static DesignVersion V0694 => new(0.6940);
    /// <summary>C++ <c>_VERSION_0695_</c> (Externs.h).</summary>
    public static DesignVersion V0695 => new(0.6950);
    /// <summary>C++ <c>_VERSION_0696_</c> (Externs.h).</summary>
    public static DesignVersion V0696 => new(0.6960);
    /// <summary>C++ <c>_VERSION_0697_</c> (Externs.h).</summary>
    public static DesignVersion V0697 => new(0.6970);
    /// <summary>C++ <c>_VERSION_0698_</c> (Externs.h).</summary>
    public static DesignVersion V0698 => new(0.6980);
    /// <summary>C++ <c>_VERSION_0699_</c> (Externs.h).</summary>
    public static DesignVersion V0699 => new(0.6990);
    /// <summary>C++ <c>_VERSION_06991_</c> (Externs.h).</summary>
    public static DesignVersion V06991 => new(0.6991);
    /// <summary>C++ <c>_VERSION_06992_</c> (Externs.h).</summary>
    public static DesignVersion V06992 => new(0.6992);
    /// <summary>C++ <c>_VERSION_0710_</c> (Externs.h).</summary>
    public static DesignVersion V0710 => new(0.7100);
    /// <summary>C++ <c>_VERSION_0720_</c> (Externs.h).</summary>
    public static DesignVersion V0720 => new(0.7200);
    /// <summary>C++ <c>_VERSION_0730_</c> (Externs.h).</summary>
    public static DesignVersion V0730 => new(0.7300);
    /// <summary>C++ <c>_VERSION_0731_</c> (Externs.h).</summary>
    public static DesignVersion V0731 => new(0.7310);
    /// <summary>C++ <c>_VERSION_0740_</c> (Externs.h).</summary>
    public static DesignVersion V0740 => new(0.7400);
    /// <summary>C++ <c>_VERSION_0750_</c> (Externs.h).</summary>
    public static DesignVersion V0750 => new(0.7500);
    /// <summary>C++ <c>_VERSION_0770_</c> (Externs.h).</summary>
    public static DesignVersion V0770 => new(0.7700);
    /// <summary>C++ <c>_VERSION_0780_</c> (Externs.h).</summary>
    public static DesignVersion V0780 => new(0.7800);
    /// <summary>C++ <c>_VERSION_0790_</c> (Externs.h).</summary>
    public static DesignVersion V0790 => new(0.7900);
    /// <summary>C++ <c>_VERSION_0800_</c> (Externs.h).</summary>
    public static DesignVersion V0800 => new(0.8000);
    /// <summary>C++ <c>_VERSION_0810_</c> (Externs.h).</summary>
    public static DesignVersion V0810 => new(0.8100);
    /// <summary>C++ <c>_VERSION_0820_</c> (Externs.h).</summary>
    public static DesignVersion V0820 => new(0.8200);
    /// <summary>C++ <c>_VERSION_0830_</c> (Externs.h).</summary>
    public static DesignVersion V0830 => new(0.8300);
    /// <summary>C++ <c>_VERSION_0840_</c> (Externs.h).</summary>
    public static DesignVersion V0840 => new(0.8400);
    /// <summary>C++ <c>_VERSION_0841_</c> (Externs.h).</summary>
    public static DesignVersion V0841 => new(0.8410);
    /// <summary>C++ <c>_VERSION_0842_</c> (Externs.h).</summary>
    public static DesignVersion V0842 => new(0.8420);
    /// <summary>C++ <c>_VERSION_0850_</c> (Externs.h).</summary>
    public static DesignVersion V0850 => new(0.8500);
    /// <summary>C++ <c>_VERSION_0851_</c> (Externs.h).</summary>
    public static DesignVersion V0851 => new(0.8510);
    /// <summary>C++ <c>_VERSION_0852_</c> (Externs.h).</summary>
    public static DesignVersion V0852 => new(0.8520);
    /// <summary>C++ <c>_VERSION_0860_</c> (Externs.h).</summary>
    public static DesignVersion V0860 => new(0.8600);
    /// <summary>C++ <c>_VERSION_0870_</c> (Externs.h).</summary>
    public static DesignVersion V0870 => new(0.8700);
    /// <summary>C++ <c>_VERSION_0880_</c> (Externs.h).</summary>
    public static DesignVersion V0880 => new(0.8800);
    /// <summary>C++ <c>_VERSION_0881_</c> (Externs.h).</summary>
    public static DesignVersion V0881 => new(0.8810);
    /// <summary>C++ <c>_VERSION_0882_</c> (Externs.h).</summary>
    public static DesignVersion V0882 => new(0.8820);
    /// <summary>C++ <c>_VERSION_0890_</c> (Externs.h).</summary>
    public static DesignVersion V0890 => new(0.8900);
    /// <summary>C++ <c>_VERSION_0900_</c> (Externs.h).</summary>
    public static DesignVersion V0900 => new(0.9000);
    /// <summary>C++ <c>_VERSION_0904_</c> (Externs.h).</summary>
    public static DesignVersion V0904 => new(0.9040);
    /// <summary>C++ <c>_VERSION_0906_</c> (Externs.h).</summary>
    public static DesignVersion V0906 => new(0.9060);
    /// <summary>C++ <c>_VERSION_0908_</c> (Externs.h).</summary>
    public static DesignVersion V0908 => new(0.9080);
    /// <summary>C++ <c>_VERSION_0909_</c> (Externs.h).</summary>
    public static DesignVersion V0909 => new(0.9090);
    /// <summary>C++ <c>_VERSION_0910_</c> (Externs.h).</summary>
    public static DesignVersion V0910 => new(0.910);
    /// <summary>C++ <c>_VERSION_0911_</c> (Externs.h).</summary>
    public static DesignVersion V0911 => new(0.911);
    /// <summary>C++ <c>_VERSION_0912_</c> (Externs.h).</summary>
    public static DesignVersion V0912 => new(0.912);
    /// <summary>C++ <c>_VERSION_0913_</c> (Externs.h).</summary>
    public static DesignVersion V0913 => new(0.913);
    /// <summary>C++ <c>_VERSION_0914_</c> (Externs.h).</summary>
    public static DesignVersion V0914 => new(0.914);
    /// <summary>C++ <c>_VERSION_0914_003</c> (Externs.h).</summary>
    public static DesignVersion V0914_003 => new(0.914003);
    /// <summary>C++ <c>_VERSION_0914_004</c> (Externs.h).</summary>
    public static DesignVersion V0914_004 => new(0.914004);
    /// <summary>C++ <c>_VERSION_0914_005</c> (Externs.h).</summary>
    public static DesignVersion V0914_005 => new(0.914005);
    /// <summary>C++ <c>_VERSION_0914_006</c> (Externs.h).</summary>
    public static DesignVersion V0914_006 => new(0.914006);
    /// <summary>C++ <c>_VERSION_0914_007</c> (Externs.h).</summary>
    public static DesignVersion V0914_007 => new(0.914007);
    /// <summary>C++ <c>_VERSION_0915_</c> (Externs.h).</summary>
    public static DesignVersion V0915 => new(0.915);
    /// <summary>C++ <c>_VERSION_0915_015</c> (Externs.h).</summary>
    public static DesignVersion V0915_015 => new(0.915015);
    /// <summary>C++ <c>_VERSION_0915_017</c> (Externs.h).</summary>
    public static DesignVersion V0915_017 => new(0.915017);
    /// <summary>C++ <c>_VERSION_0915_041</c> (Externs.h).</summary>
    public static DesignVersion V0915_041 => new(0.915041);
    /// <summary>C++ <c>_VERSION_0915_045</c> (Externs.h).</summary>
    public static DesignVersion V0915_045 => new(0.915045);
    /// <summary>C++ <c>_VERSION_0916</c> (Externs.h).</summary>
    public static DesignVersion V0916 => new(0.916);
    /// <summary>C++ <c>_VERSION_0920_000</c> (Externs.h).</summary>
    public static DesignVersion V0920_000 => new(0.920000);
    /// <summary>C++ <c>_VERSION_0930</c> (Externs.h).</summary>
    public static DesignVersion V0930 => new(0.930);
    /// <summary>C++ <c>VersionSpellIDs</c> (Globals.cpp).</summary>
    public static DesignVersion SpellIDs => new(0.998100);
    /// <summary>C++ <c>VersionSpellNames</c> (Globals.cpp).</summary>
    public static DesignVersion SpellNames => new(0.998101);
    /// <summary>C++ <c>VersionSaveIDs</c> (Globals.cpp).</summary>
    public static DesignVersion SaveIDs => new(0.998914);
    /// <summary>C++ <c>_CELL_CONTENTS_VERSION</c> (Externs.h).</summary>
    public static DesignVersion CellContents => new(5.0);
    /// <summary>C++ <c>_VERSION_524</c> (Externs.h).</summary>
    public static DesignVersion V524 => new(5.24);
    /// <summary>C++ <c>_VERSION_525</c> (Externs.h).</summary>
    public static DesignVersion V525 => new(5.25);
    /// <summary>C++ <c>_VERSION_526</c> (Externs.h).</summary>
    public static DesignVersion V526 => new(5.26);
    /// <summary>C++ <c>_VERSION_527</c> (Externs.h).</summary>
    public static DesignVersion V527 => new(5.27);
    /// <summary>C++ <c>_VERSION_528</c> (Externs.h).</summary>
    public static DesignVersion V528 => new(5.28);
    /// <summary>C++ <c>_VERSION_529</c> (Externs.h).</summary>
    public static DesignVersion V529 => new(5.29);
    /// <summary>C++ <c>PRODUCT_VER</c> (Globals.cpp).</summary>
    public static DesignVersion Product => new(5.29);
    /// <summary>C++ <c>ENGINE_VER</c> (Globals.cpp).</summary>
    public static DesignVersion Engine => new(5.29);

    // Aliases (C++ #defines pointing at another constant).
    /// <summary>C++ <c>_ITEM_DB_VERSION_</c> (Externs.h), an alias for <see cref="V0560"/>.</summary>
    public static DesignVersion ItemDb => V0560;
    /// <summary>C++ <c>_SPELL_DB_VERSION_</c> (Externs.h), an alias for <see cref="V0560"/>.</summary>
    public static DesignVersion SpellDb => V0560;
    /// <summary>C++ <c>_MONSTER_DB_VERSION_</c> (Externs.h), an alias for <see cref="V0500"/>.</summary>
    public static DesignVersion MonsterDb => V0500;
    /// <summary>C++ <c>_SPECIAL_ABILITIES_VERSION_</c> (Externs.h), an alias for <see cref="V0930"/>.</summary>
    public static DesignVersion SpecialAbilities => V0930;

    /// <summary>Every constant transcribed from the C++ tree (98 total).</summary>
    public static System.Collections.Generic.IReadOnlyList<DesignVersion> All { get; } =
    [
        V0500,
        V0505,
        V0560,
        V0563,
        V0564,
        V0566,
        V05661,
        V05662,
        V0569,
        V05691,
        V0572,
        V0573,
        V0574,
        V0575,
        V0576,
        V05771,
        V0600,
        V0620,
        V0630,
        V0640,
        V0642,
        V0660,
        V0661,
        V0662,
        V0670,
        V0681,
        V0682,
        V0690,
        V0692,
        V0693,
        V0694,
        V0695,
        V0696,
        V0697,
        V0698,
        V0699,
        V06991,
        V06992,
        V0710,
        V0720,
        V0730,
        V0731,
        V0740,
        V0750,
        V0770,
        V0780,
        V0790,
        V0800,
        V0810,
        V0820,
        V0830,
        V0840,
        V0841,
        V0842,
        V0850,
        V0851,
        V0852,
        V0860,
        V0870,
        V0880,
        V0881,
        V0882,
        V0890,
        V0900,
        V0904,
        V0906,
        V0908,
        V0909,
        V0910,
        V0911,
        V0912,
        V0913,
        V0914,
        V0914_003,
        V0914_004,
        V0914_005,
        V0914_006,
        V0914_007,
        V0915,
        V0915_015,
        V0915_017,
        V0915_041,
        V0915_045,
        V0916,
        V0920_000,
        V0930,
        SpellIDs,
        SpellNames,
        SaveIDs,
        CellContents,
        V524,
        V525,
        V526,
        V527,
        V528,
        V529,
        Product,
        Engine,
    ];
}
