#!/usr/bin/env python3
"""Generate UAFcore/PartyArrangements.Generated.cs from src/UAFWin/Combatants.cpp.

The two party formation tables -- partyIndoorCombatArrangement and
partyOutdoorCombatArrangement (Combatants.cpp:2303, :2323) -- are each 624 characters of
positional data written as ~50 adjacent C string literals. Two characters give one party member's
(dx, dy) offset from the party origin, so a single dropped or transposed character silently moves
somebody, and there is no framing to notice it.

Layout: four direction blocks (north, east, south, west) of 156 characters each; within a block,
twelve runs for party sizes 1..12, run n being 2n characters long. The offset of a member is

    direction * (MAX_PARTY_MEMBERS + 1) * MAX_PARTY_MEMBERS
        + (partySize - 1) * partySize
        + 2 * memberIndex

Both files carry large commented-out earlier versions of the same tables, including one *after*
the terminating semicolon, so the extraction stops at the semicolon and strips comments first.

Usage:  python3 dotnet/tools/gen-party-arrangements.py [--check]
        --check exits non-zero if the checked-in file is stale (for CI).
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SRC = REPO / "src" / "UAFWin" / "Combatants.cpp"
OUT = REPO / "dotnet" / "src" / "UAFcore" / "PartyArrangements.Generated.cs"

MAX_PARTY_MEMBERS = 12
BLOCK = (MAX_PARTY_MEMBERS + 1) * MAX_PARTY_MEMBERS      # 156 chars per direction
EXPECTED = 4 * BLOCK                                      # 624

RE_STRING = re.compile(r'"([^"]*)"')


def extract(text: str, name: str) -> str:
    """Concatenate the string literals of `char <name>[...] = ... ;`."""
    start = text.index(f"char {name}[")
    body = text[start:]
    # Strip block comments first -- partyOutdoorCombatArrangement is followed by a commented-out
    # copy of itself, and a naive scan for the semicolon would sail past it.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    # Then line comments, which is how the older indoor table is disabled.
    body = re.sub(r"//[^\n]*", "", body)
    body = body[: body.index(";")]
    # Drop the declaration itself, so the array bound's literals cannot be picked up.
    body = body[body.index("=") + 1 :]
    return "".join(RE_STRING.findall(body))


def runs(table: str) -> list[list[str]]:
    """Split a table into 4 directions x 12 party sizes, for the generated comments."""
    out = []
    for d in range(4):
        block = table[d * BLOCK : (d + 1) * BLOCK]
        sizes, at = [], 0
        for size in range(1, MAX_PARTY_MEMBERS + 1):
            sizes.append(block[at : at + 2 * size])
            at += 2 * size
        out.append(sizes)
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = SRC.read_text(encoding="utf-8", errors="replace")

    tables = {}
    for cpp_name, cs_name in (("partyIndoorCombatArrangement", "Indoor"),
                              ("partyOutdoorCombatArrangement", "Outdoor")):
        table = extract(text, cpp_name)
        if len(table) != EXPECTED:
            print(f"error: {cpp_name} came out {len(table)} chars, expected {EXPECTED}",
                  file=sys.stderr)
            return 1
        # Every character must decode: A-Z, a-z. Anything else means the scan picked up stray text.
        bad = {c for c in table if not c.isalpha()}
        if bad:
            print(f"error: {cpp_name} has non-alphabetic characters {sorted(bad)}", file=sys.stderr)
            return 1
        tables[cs_name] = table

    lines = [
        "// <auto-generated>",
        "//     Generated by dotnet/tools/gen-party-arrangements.py from src/UAFWin/Combatants.cpp.",
        "//     Do not edit by hand; re-run the generator and diff.",
        "// </auto-generated>",
        "",
        "namespace UAFcore;",
        "",
        "public static partial class PartyArrangements",
        "{",
        f"    /// <summary>Longest party the tables describe (<c>MAX_PARTY_MEMBERS</c>).</summary>",
        f"    public const int MaxPartyMembers = {MAX_PARTY_MEMBERS};",
        "",
        f"    /// <summary>Characters per direction block.</summary>",
        f"    public const int DirectionBlock = {BLOCK};",
        "",
    ]

    for cs_name, table in tables.items():
        cpp = ("partyIndoorCombatArrangement" if cs_name == "Indoor"
               else "partyOutdoorCombatArrangement")
        lines += [
            f"    /// <summary>",
            f"    /// <c>{cpp}</c> — four direction blocks of {BLOCK} characters.",
            f"    /// </summary>",
            f"    /// <remarks>",
            f"    /// <code>",
        ]
        for d, name in enumerate(("north", "east", "south", "west")):
            sizes = runs(table)[d]
            lines.append(f"    /// {name}:")
            for n, run in enumerate(sizes, start=1):
                lines.append(f"    ///   {n:2d}: {run}")
        lines += [
            f"    /// </code>",
            f"    /// </remarks>",
            f'    public const string {cs_name} =',
        ]
        # 78 characters per source line keeps the literal readable and inside the line limit.
        for at in range(0, len(table), 78):
            chunk = table[at : at + 78]
            terminator = ";" if at + 78 >= len(table) else " +"
            lines.append(f'        "{chunk}"{terminator}')
        lines.append("")

    lines[-1] = "}"
    out_text = "\n".join(lines) + "\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != out_text:
            print("error: PartyArrangements.Generated.cs is stale; re-run "
                  "dotnet/tools/gen-party-arrangements.py", file=sys.stderr)
            return 1
        print(f"up to date ({', '.join(f'{k}: {len(v)}' for k, v in tables.items())})")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out_text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    for name, table in tables.items():
        print(f"  {name}: {len(table)} chars, north/size-3 = {runs(table)[0][2]!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
