#!/usr/bin/env python3
"""Generate UAF.Common/DesignVersion.Generated.cs from the legacy C++ headers.

Version constants live in three places in the C++ tree (see docs/PORTING-PLAN.md section 3):

  * src/Shared/Externs.h   -- 92 `#define _VERSION_xxx  <double>` macros, plus named aliases
  * src/Shared/Globals.cpp -- 5 `extern const double <Name> = <double>;` definitions
  * src/Shared/ProjectVersion.h -- DEAD (entirely commented out, stale). Deliberately ignored.

Transcribing ~97 six-decimal doubles by hand is a silent-one-digit-error factory, so we
generate instead. Re-run after any change to the C++ headers and diff the result.

Usage:  python3 dotnet/tools/gen-design-versions.py [--check]
        --check exits non-zero if the checked-in file is stale (for CI).
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
EXTERNS = REPO / "src" / "Shared" / "Externs.h"
GLOBALS = REPO / "src" / "Shared" / "Globals.cpp"
OUT = REPO / "dotnet" / "src" / "UAF.Common" / "DesignVersion.Generated.cs"

# `#define _VERSION_0914_003 0.914003`  /  `#define _VERSION_529      5.29`
RE_VERSION_MACRO = re.compile(r"^#define\s+(_VERSION_[A-Za-z0-9_]*)\s+([0-9]*\.[0-9]+)\s*$", re.M)
# `#define _SPECIAL_ABILITIES_VERSION_   _VERSION_0930`  (alias to another macro)
RE_ALIAS_MACRO = re.compile(r"^#define\s+(_[A-Z][A-Z_0-9]*VERSION[A-Z_]*)\s+(_VERSION_[A-Za-z0-9_]*)\s*$", re.M)
# `#define _CELL_CONTENTS_VERSION        5.0`  (named, literal value)
RE_NAMED_LITERAL = re.compile(r"^#define\s+(_[A-Z][A-Z_0-9]*VERSION[A-Z_]*)\s+([0-9]*\.[0-9]+)\s*$", re.M)
# `extern const double VersionSaveIDs = 0.998914;`
RE_EXTERN_DOUBLE = re.compile(r"^extern\s+const\s+double\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([0-9]*\.[0-9]+)\s*;", re.M)


def csharp_name(cpp: str) -> str:
    """_VERSION_0914_003 -> V0914_003 ; _SPECIAL_ABILITIES_VERSION_ -> SpecialAbilities ;
    VersionSpellNames -> SpellNames ; PRODUCT_VER -> Product"""
    if cpp.startswith("_VERSION_"):
        return "V" + cpp[len("_VERSION_"):].strip("_")
    if cpp.startswith("Version"):
        return cpp[len("Version"):]
    if cpp in ("PRODUCT_VER", "ENGINE_VER"):
        return {"PRODUCT_VER": "Product", "ENGINE_VER": "Engine"}[cpp]
    words = [w for w in cpp.strip("_").split("_") if w and w != "VERSION"]
    return "".join(w.capitalize() for w in words)


def literal(value: str) -> str:
    """Preserve the exact decimal text from the C++ source; never reformat."""
    return value if value.startswith("0.") or "." in value else value + ".0"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    externs = EXTERNS.read_text(encoding="utf-8", errors="replace")
    globals_ = GLOBALS.read_text(encoding="utf-8", errors="replace")

    entries: list[tuple[str, str, str, str]] = []  # (csname, literal, cppname, origin)
    seen: dict[str, str] = {}

    def add(cppname: str, value: str, origin: str) -> None:
        cs = csharp_name(cppname)
        if cs in seen:
            if seen[cs] != value:
                print(f"error: {cs} defined twice with different values "
                      f"({seen[cs]} vs {value})", file=sys.stderr)
                raise SystemExit(2)
            return
        seen[cs] = value
        entries.append((cs, literal(value), cppname, origin))

    for m in RE_VERSION_MACRO.finditer(externs):
        add(m.group(1), m.group(2), "Externs.h")
    for m in RE_NAMED_LITERAL.finditer(externs):
        add(m.group(1), m.group(2), "Externs.h")
    for m in RE_EXTERN_DOUBLE.finditer(globals_):
        add(m.group(1), m.group(2), "Globals.cpp")

    aliases: list[tuple[str, str, str]] = []
    for m in RE_ALIAS_MACRO.finditer(externs):
        target_cs = csharp_name(m.group(2))
        if target_cs in seen:
            aliases.append((csharp_name(m.group(1)), target_cs, m.group(1)))

    entries.sort(key=lambda e: float(e[1]))

    lines: list[str] = [
        "// <auto-generated>",
        "//     Generated by dotnet/tools/gen-design-versions.py from the legacy C++ headers.",
        "//     Do not edit by hand. Re-run the generator and commit the result instead.",
        "//",
        "//     Sources: src/Shared/Externs.h, src/Shared/Globals.cpp",
        "//     (src/Shared/ProjectVersion.h is dead code and is deliberately ignored.)",
        "// </auto-generated>",
        "",
        "namespace UAF.Common;",
        "",
        "public readonly partial struct DesignVersion",
        "{",
    ]
    for cs, lit, cpp, origin in entries:
        lines.append(f"    /// <summary>C++ <c>{cpp}</c> ({origin}).</summary>")
        lines.append(f"    public static DesignVersion {cs} => new({lit});")
    if aliases:
        lines.append("")
        lines.append("    // Aliases (C++ #defines pointing at another constant).")
        for cs, target, cpp in aliases:
            lines.append(f"    /// <summary>C++ <c>{cpp}</c> (Externs.h), an alias for <see cref=\"{target}\"/>.</summary>")
            lines.append(f"    public static DesignVersion {cs} => {target};")
    lines.append("")
    lines.append(f"    /// <summary>Every constant transcribed from the C++ tree ({len(entries)} total).</summary>")
    lines.append("    public static System.Collections.Generic.IReadOnlyList<DesignVersion> All { get; } =")
    lines.append("    [")
    for cs, _, _, _ in entries:
        lines.append(f"        {cs},")
    lines.append("    ];")
    lines.append("}")
    text = "\n".join(lines) + "\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("error: DesignVersion.Generated.cs is stale; re-run "
                  "dotnet/tools/gen-design-versions.py", file=sys.stderr)
            return 1
        print(f"up to date ({len(entries)} constants, {len(aliases)} aliases)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(entries)} constants, {len(aliases)} aliases")
    print(f"  range: {entries[0][1]} ({entries[0][0]}) .. {entries[-1][1]} ({entries[-1][0]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
