#!/usr/bin/env python3
"""Generate UAFcore/CombatTiles.Generated.cs from src/UAFWin/Drawtile.cpp.

The two combat terrain tile tables -- DungeonWallTiles (27 rows) and WildernessWallTiles (41
rows) -- are plain C arrays of `{ posx, posy, invisible, passable, enabled }`. That is 340
integers whose only structure is their position, which makes hand-transcription exactly the kind
of silent-one-digit error docs/PORTING-PLAN.md section 11 says to generate away rather than proofread.

Two fields drive engine behaviour rather than drawing, so a transposed column is not a cosmetic
bug: `invisible` gates line-of-sight (HaveVisibility, Drawtile.cpp:1305) and `passable` gates
movement (HaveMovability, Drawtile.cpp:1336).

Note the field name `tile_invisible` reads backwards: 1 means see-through, per the comment block
at Drawtile.cpp:205. The generated C# renames it SeeThrough.

Row 0 of each table is a placeholder the original never indexes -- every lookup is guarded by
`cell < 1` -- but it is emitted so the C# indices line up with the C++ ones.

Usage:  python3 dotnet/tools/gen-combat-tiles.py [--check]
        --check exits non-zero if the checked-in file is stale (for CI).
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SRC = REPO / "src" / "UAFWin" / "Drawtile.cpp"
OUT = REPO / "dotnet" / "src" / "UAFcore" / "CombatTiles.Generated.cs"

# `TILE_DATA DungeonWallTiles[DUNGEON_TILE_COUNT+1] = { ... };`
RE_TABLE = re.compile(
    r"TILE_DATA\s+(\w+)\s*\[\s*(\w+)\s*\+\s*1\s*\]\s*=\s*\{(.*?)\n\}\s*;",
    re.S,
)
# `{   242,62,1,1,1 },  // 15`   -- five integers, optional trailing comment
RE_ROW = re.compile(r"\{\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}")
# `const int DUNGEON_TILE_COUNT = 26;` / `const int DUNGEON_EMPTY_TILE = 23;`
RE_CONST = re.compile(r"^const\s+int\s+(\w+)\s*=\s*(\d+)\s*;", re.M)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = SRC.read_text(encoding="utf-8", errors="replace")
    consts = {m.group(1): int(m.group(2)) for m in RE_CONST.finditer(text)}

    tables: dict[str, list[tuple[int, ...]]] = {}
    for m in RE_TABLE.finditer(text):
        name, count_macro, body = m.group(1), m.group(2), m.group(3)
        rows = [tuple(int(g) for g in r.groups()) for r in RE_ROW.finditer(body)]
        expected = consts.get(count_macro)
        if expected is None:
            print(f"error: no value for {count_macro}", file=sys.stderr)
            return 1
        # The declared bound is COUNT+1, so a complete table has COUNT+1 rows including row 0.
        if len(rows) != expected + 1:
            print(f"error: {name} has {len(rows)} rows, expected {expected + 1}", file=sys.stderr)
            return 1
        tables[name] = rows

    for required in ("DungeonWallTiles", "WildernessWallTiles"):
        if required not in tables:
            print(f"error: {required} not found in {SRC}", file=sys.stderr)
            return 1

    lines = [
        "// <auto-generated>",
        "//     Generated by dotnet/tools/gen-combat-tiles.py from src/UAFWin/Drawtile.cpp.",
        "//     Do not edit by hand; re-run the generator and diff.",
        "// </auto-generated>",
        "",
        "namespace UAFcore;",
        "",
        "public static partial class CombatTiles",
        "{",
    ]

    emitted = []
    for cpp_name, cs_name, empty_const in (
        ("DungeonWallTiles", "Dungeon", "DUNGEON_EMPTY_TILE"),
        ("WildernessWallTiles", "Wilderness", "WILDERNESS_EMPTY_TILE"),
    ):
        rows = tables[cpp_name]
        empty = consts[empty_const]
        emitted.append((cs_name, len(rows), empty))

        lines += [
            f"    /// <summary>",
            f"    /// <c>{cpp_name}</c> — {len(rows) - 1} tiles, index 0 unused.",
            f"    /// </summary>",
            f"    public static readonly CombatTile[] {cs_name} =",
            "    [",
        ]
        for i, (px, py, invis, passable, enabled) in enumerate(rows):
            comment = "   // unused placeholder" if i == 0 else f"   // {i}"
            lines.append(
                f"        new({px}, {py}, "
                f"SeeThrough: {str(invis != 0).lower()}, "
                f"Passable: {str(passable != 0).lower()}, "
                f"Enabled: {str(enabled != 0).lower()}),{comment}"
            )
        lines += ["    ];", ""]

        lines += [
            f"    /// <summary>The tile holes in the {cs_name.lower()} map are filled with"
            f" (<c>{empty_const}</c>).</summary>",
            f"    public const int {cs_name}EmptyTile = {empty};",
            "",
        ]

    lines[-1] = "}"
    out_text = "\n".join(lines) + "\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != out_text:
            print("error: CombatTiles.Generated.cs is stale; re-run "
                  "dotnet/tools/gen-combat-tiles.py", file=sys.stderr)
            return 1
        print("up to date (" + ", ".join(f"{n}: {c}" for n, c, _ in emitted) + ")")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(out_text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    for name, count, empty in emitted:
        print(f"  {name}: {count} rows (index 0 unused), empty tile {empty}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
